build: false
shallow_clone: true
platform: 'x86'

init:
    - SET PATH=C:\Program Files\OpenSSL;c:\tools\php71;%PATH%
    - SET COMPOSER_NO_INTERACTION=1
    - SET PHP=1
    - SET ANSICON=121x90 (121x90)

install:
    - ps: Set-Service wuauserv -StartupType Manual
    - IF EXIST c:\tools\php71 (SET PHP=0)
    - IF %PHP%==1 cinst -y php --version 7.1.3
    - IF %PHP%==1 cd c:\tools\php71
    - IF %PHP%==1 copy php.ini-production php.ini
    - IF %PHP%==1 echo extension=php_mbstring.dll >> php.ini
    - SET PATH=C:\tools\php71;%PATH%
    - cd %APPVEYOR_BUILD_FOLDER%
    - appveyor DownloadFile https://getcomposer.org/composer.phar
    - php composer.phar install --prefer-dist -n --no-ansi
test_script:
    - php vendor/bin/phpunit